- xopt/cmoo.py
Version 0.5.0 of pymoo had breaking changes.
More details here: https://github.com/anyoptimization/pymoo/releases/tag/0.5.0
> FIX: Compatibility with new pymoo version.

- .pre-commit-config.yaml
- README.md
- environment.yml
Implements hooks for ufmt formatting, flake8, and pytest runs
> Implement pre-commit hooks

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- test-requirements.txt
- Add flake8 to testing and exclude yaml files from pre-commit hooks
> Add flake8 to testing

- mkdocs.yml
This fixes https://github.com/ChristopherMayes/Xopt/issues/80
> Fix paths to some notebooks in docs

- tests/generators/bayesian/test_bayesian_generator.py
- xopt/generators/bayesian/bayesian_generator.py
> fix max travel distances bug

- xopt/generators/bayesian/multi_fidelity.py
- xopt/utils.py
This removes the package-level dependency on matplotlib for a utility function, instead uses a lazy import.
> lazy import matplotlib

- tests/generators/bayesian/test_expected_improvement.py
- xopt/generators/bayesian/custom_botorch/constrained_acqusition.py
- xopt/generators/bayesian/expected_improvement.py
Fixes the calculation of the best observed value and adds a test for acquisition accuracy.
> Fix acquisition for ExpectedImprovementGenerator

- tests/generators/bayesian/test_bax.py
- tests/generators/bayesian/test_expected_improvement.py
- tests/generators/bayesian/test_model_constructor.py
- xopt/generators/bayesian/custom_botorch/constrained_acqusition.py
- xopt/generators/bayesian/models/prior_mean.py
- xopt/generators/bayesian/models/standard.py
- xopt/generators/bayesian/models/trainable_mean.py
- xopt/generators/bayesian/models/transformed_model.py
- xopt/generators/bayesian/turbo.py
- xopt/vocs.py
fixes bug where custom covariance modules are not trained from scratch at each iteration, also formatting
> model constructor bugfix

- tests/generators/bayesian/test_custom_model.py
- xopt/generators/bayesian/bayesian_exploration.py
- xopt/generators/bayesian/bayesian_generator.py
- xopt/generators/bayesian/models/prior_mean.py
Fixes an incorrect default value in the CustomMean constructor and adds a test for trainable prior means.
> Fix CustomMean

- environment.yml
- requirements.txt
pydantic 2.0 has been released and we do not support it yet
> pip pydantic version for now

- xopt/generators/bayesian/bayesian_generator.py
- xopt/generators/bayesian/expected_improvement.py
- xopt/generators/bayesian/upper_confidence_bound.py
- changes computation of UCB and EI from analytic to mc sampling depending on the number of candidates requested for generation - leads to ~20% computation time decrease at 100 points
> Adaptive ucb ei

- tests/generators/bayesian/test_turbo.py
- tests/test_xopt.py
- xopt/base.py
- xopt/generators/bayesian/turbo.py
- also addresses a bug in Xopt base class that fixes printing
> bugfix for using turbo with maximization + test

- tests/generators/bayesian/test_high_level.py
- xopt/base.py
- Fixes a bug causing data not to be reloaded in generators from xopt object when using Xopt parse_obj
> implement and test data saving + restart bugfix

- docs/examples/single_objective_bayes_opt/bo_tutorial.ipynb
- docs/examples/single_objective_bayes_opt/constrained_bo_tutorial.ipynb
- docs/examples/single_objective_bayes_opt/heteroskedastic_noise_tutorial.ipynb
- docs/examples/single_objective_bayes_opt/noisy_bo_tutorial.ipynb
- docs/examples/single_objective_bayes_opt/turbo_tutorial.ipynb
- tests/generators/bayesian/test_upper_confidence_bound.py
- xopt/generators/bayesian/bayesian_generator.py
- xopt/generators/bayesian/custom_botorch/constrained_acquisition.py
- xopt/generators/bayesian/custom_botorch/constrained_acqusition.py
- xopt/generators/bayesian/multi_fidelity.py
- xopt/generators/bayesian/objectives.py
- xopt/generators/bayesian/upper_confidence_bound.py
Adds warnings if UCB is used in conjunction with constraints or large negative values of the base acquisition function are encountered. Also fixes some typos.
> UCB and constraints

- docs/examples/basic/xopt_vocs.ipynb
- tests/test_xopt.py
- xopt/__init__.py
- xopt/base.py
- xopt/pydantic.py
> add from_file helper function

- docs/index.md
This updates the main page in docs to align with the README.md in the root.
> Update main index page in docs

- tests/test_vocs.py
- xopt/generators/bayesian/visualize.py
- xopt/vocs.py
- add method to vocs that id's the best index and value of a data frame based on vocs
- ignores points that do not satisfy all constraints
> add select_best function to vocs

- README.md
- docs/index.md
- mkdocs.yml
Small touchups
- remove expected improvement link
- link to IPAC23 paper
> Docs touchup

- tests/generators/bayesian/test_custom_model.py
- tests/test_xopt.py
- xopt/base.py
- xopt/generators/bayesian/visualize.py
- xopt/vocs.py
fixes a bug where indexing in xopt.data skips indices when calling add data
> bugfix for pandas indexing issue

- xopt/generators/bayesian/visualize.py
Adds `show_acquisition` flag to turn off computation of the acquisition function for model visualization.
> Adds a flag to turn off aquisition function for visualization

- xopt/generators/bayesian/visualize.py
Fixes an indexing error occurring for model visualization with a single objective and `show_acquisition=False`.
> Fix indexing error for model visualization

- tests/generators/bayesian/test_model_constructor.py
- xopt/generators/bayesian/models/standard.py
Modifies the `StandardModelConstructor` to raise warnings if covariance or mean modules are specified, but not added to the model (e.g. because of incorrect output names). Fixes #197.
> Add warnings if specified modules are not added to the model

- xopt/generators/bayesian/custom_botorch/constrained_acquisition.py
- xopt/generators/bayesian/multi_fidelity.py
- xopt/generators/bayesian/objectives.py
- xopt/generators/bayesian/turbo.py
- xopt/generators/bayesian/visualize.py
- xopt/resources/test_functions/sphere_100.py
- xopt/resources/test_functions/sphere_20.py
- xopt/resources/test_functions/sphere_50.py
also adds a fix for bugs introduced by using botorch 0.10.0
> add test functions and set rasterize for colormaps

- docs/examples/basic/xopt_generator.ipynb
- mkdocs.yml
- tests/test_vocs.py
- xopt/base.py
- xopt/evaluator.py
- xopt/generators/bayesian/models/standard.py
- xopt/vocs.py
+ add docstring info to executor RE: vectorize flag
> make random evaluate consistent with numpy standards

- xopt/generators/bayesian/visualize.py
Improves the error message for attempting visualization with an invalid number of variables. Fixes #214.
> Improve Visualization Error Message

- tests/test_vocs.py
- xopt/vocs.py
also adds more tests for constraint specification
> fix a bug with type checking vocs constraints

- tests/generators/bayesian/test_utils.py
- xopt/generators/bayesian/bayesian_exploration.py
- xopt/generators/bayesian/bayesian_generator.py
- xopt/generators/bayesian/expected_improvement.py
- xopt/generators/bayesian/mggpo.py
- xopt/generators/bayesian/mobo.py
- xopt/generators/bayesian/objectives.py
- xopt/generators/bayesian/upper_confidence_bound.py
- xopt/generators/bayesian/utils.py
- xopt/generators/bayesian/visualize.py
fixes a bug with setting objective weights, this is a major bugfix for bayesian exploration which was exploring the constraint instead of the observable
> Set weights bugfix that creates improper behavior for bayesian exploration

- tests/test_vocs.py
- xopt/vocs.py
- add validation of variable specification to vocs
- also add warnings and errors to random variable specification
> Error handling for vocs

- .github/workflows/pypi_upload.yml
This should fix the previous PyPI upload problem.
> Fix PyPI update to Python 3.9

- .github/workflows/pypi_upload.yml
This updates the PyPI upload action according to https://github.com/pypa/gh-action-pypi-publish
> update according to https://github.com/pypa/gh-action-pypi-publish

- .pre-commit-config.yaml
- xopt/tests/generators/sequential/test_neldermead.py
- xopt/tests/test_xopt.py
- updated hook versions
- formatted files
> ruff formatting update

- xopt/generators/bayesian/bax_generator.py
- xopt/generators/bayesian/bayesian_exploration.py
- xopt/generators/bayesian/bayesian_generator.py
- xopt/generators/bayesian/expected_improvement.py
- xopt/generators/bayesian/turbo.py
- xopt/generators/bayesian/upper_confidence_bound.py
- xopt/generators/bayesian/utils.py
- xopt/tests/generators/bayesian/test_bayesian_exploration.py
- xopt/tests/generators/bayesian/test_turbo.py
- also remove incorrect statement from safety turbo controller
- Addresses #295
> implement better turbo validation

- xopt/generator.py
- xopt/generators/__init__.py
- xopt/generators/bayesian/bax_generator.py
- xopt/generators/bayesian/bayesian_exploration.py
- xopt/generators/bayesian/expected_improvement.py
- xopt/generators/bayesian/mggpo.py
- xopt/generators/bayesian/mobo.py
- xopt/generators/bayesian/time_dependent.py
- xopt/generators/bayesian/upper_confidence_bound.py
- xopt/generators/ga/cnsga.py
- xopt/generators/ga/nsga2.py
- xopt/generators/random.py
- xopt/generators/scipy/latin_hypercube.py
- xopt/generators/sequential/extremumseeking.py
- xopt/generators/sequential/neldermead.py
- xopt/generators/sequential/rcds.py
- xopt/tests/generators/bayesian/test_bayesian_generator.py
- xopt/tests/generators/bayesian/test_turbo.py
- xopt/tests/generators/sequential/test_extremum_seeking.py
- xopt/tests/generators/sequential/test_neldermead.py
- xopt/tests/generators/sequential/test_rcds.py
- xopt/tests/generators/sequential/test_sequential.py
- xopt/tests/test_generator.py
- xopt/tests/test_xopt.py
This pull request introduces several enhancements to the generator classes in the `xopt` package, focusing on adding support for single-objective and constrained optimization. The most significant changes include the addition of new fields to the `Generator` class, updates to the validation logic, and modifications to various generator subclasses to support these new features.
Enhancements to generator capabilities:
* [`xopt/generator.py`](diffhunk://#diff-bee960579cd21ad1d0c6417e8c9e8ff53b4d19257aa339ba171975aba68cfb92R54-R67): Added `supports_single_objective` and `supports_constraints` fields to the `Generator` class, and updated the `validate_vocs` method to include checks for these new fields. [[1]](diffhunk://#diff-bee960579cd21ad1d0c6417e8c9e8ff53b4d19257aa339ba171975aba68cfb92R54-R …
> Vocs validation

- xopt/generators/bayesian/bayesian_generator.py
- xopt/tests/generators/bayesian/test_mobo.py
- if the reference point is in the non-dominated set then the entire set is not on the PF
> fix edge case where data points are not dominated by the reference point

- xopt/generator.py
- xopt/generators/bayesian/bayesian_generator.py
- xopt/tests/generators/bayesian/test_bax.py
- xopt/tests/generators/bayesian/test_bayesian_exploration.py
- xopt/tests/generators/bayesian/test_bayesian_generator.py
- xopt/tests/generators/bayesian/test_mobo.py
- xopt/tests/generators/bayesian/test_turbo.py
- xopt/tests/test_generator.py
Fixes #303 
TODO: rework the solution in long term if field validation order can be tricked somehow
> Fix VOCS/MOBO validation issues and improve handling

- environment.yml
- pyproject.toml
- xopt/tests/test_numerical_optimizer.py
Small test fix on our end to make tests compatible with feasibility masking in botorch 0.14
> Fix botorch 0.14 compatibility

- xopt/utils.py
Addresses issue in which get_local_region() function was proposing points that were potentially outside of the variable bounds.
> Fix get_local_region to ensure proposed points do not violate bounds.

- xopt/generators/bayesian/visualize.py
- Added missing `interactive` arg to several functions that default to False so no error was thrown in initial PR #348
> Added missing arg to functions from prior PR
