- .pre-commit-config.yaml
No one deserves to feel the pain of a black-formatted-for-python ipynb json file.
> Add ipynb exclusion to pre commit

- tests/test_pydantic.py
- xopt/pydantic.py
In addition to adding pydantic tests, I changed the validate_and_compose_signature method to return a custom pydantic model for the signature. This centralized the handling. All args, kwargs, + positional or kwargs are handled in this change.
> Check in pydantic tests and change the sig composition

- tests/test_evaluator.py
- xopt/evaluator.py
- xopt/generators/bayesian/models/standard.py
Pandas Dataframe `iterrows()` does not preserve dtype!
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iterrows.html#pandas.DataFrame.iterrows
This is a possible fix with dataframe `df`:
`for index, row in df.iterrows():` -> `for index, row in zip(df.index, df.to_dict(orient="records")): `
The following should be more efficient:
```python
for named_tuple in df.itertuples():
row = named_tuple._asdict()
index = row.pop("Index")
```
> Remove iterrows

- tests/test_evaluator.py
- xopt/evaluator.py
Pandas Dataframe `itertuples` does not preserve `_` or `:` in column names. This pattern does:
```python
for index, row_dict in zip(df.index, df.to_dict("records")):
```
Also see: https://github.com/pandas-dev/pandas/issues/23848
> remove itertuples and add more tests

- environment.yml
- requirements.txt
Resolves unexplained Python 3.9 issues with not skipping executor during model serialization
> Bump pydantic version

- xopt/generators/scipy/neldermead.py
- xopt/resources/test_functions/rosenbrock.py
This fixes a bug where the constants were not filled from inputs from the generator. In other generators this is usually handled with `vocs.convert_dataframe_to_inputs`
> Fix constants in neldermean

- .github/workflows/examples.yml
- environment.yml
- requirements.txt
- scripts/run_examples.py
- tests/generators/bayesian/test_bayesian_options.py
- tests/test_evaluator.py
- xopt/generators/bayesian/__init__.py
- xopt/generators/bayesian/multi_fidelity.py
- xopt/generators/bayesian/options.py
- xopt/pydantic.py
- rewrites pydantic serialization of xopt options to increase flexibility
- enables serialization of pytorch modules -> saves model using torch.save and replaces module with file location
- enables (de)serialization of pytorch files for modules in options
> Model serialization

- xopt/generators/bayesian/turbo.py
fixes a bug in turbo that incorrectly calculates the normalization constant that ensures the bounding box remains the same volume
> Bugfix turbo

- tests/test_utils.py
- xopt/utils.py
This PR adds a method to create a deep copy of a generator object. This method will also move any data saved on the gpu in the copied object to the cpu for torch.Tensor and torch.nn.Module objects.   
The intention of this method it to make it easy to save the current state of the generator at a given step.
Unit tests for the new methods were added 
The method has a comment describing itself at the top of the method which should be added by the auto documentation.
> ENH: Untility method to copy generator objects

- xopt/generators/bayesian/bayesian_generator.py
Deletes a print statement called during validation of the GP constructor.
> Delete print statement for validation of GP constructor

- test-requirements.txt
The `test-requirements.txt` file does not appear to be in use at this point.
However, it currently contains a typo of the `pytest-cov` package, meaning it wouldn't install properly as-is.
> BLD: fix test requirements

- tests/generators/ga/test_cnsga.py
- xopt/generators/ga/cnsga.py
As reported by a user, in rare cases of repeat dataframe indices, CNSGA population can grow out of control because the next generation is selected via .loc method that can match multiple rows per value. This PR switches selection to use positional indexing.
> Fix CNSGA population selection

- tests/test_vocs.py
- tests/test_xopt.py
- xopt/asynchronous.py
- xopt/base.py
- xopt/generators/bayesian/visualize.py
- xopt/resources/testing.py
This addresses #195 by adding constants to the inputs prepared in `AsynchronousXopt`. This also modifies the tests.
> Fix constants not propagating in AsynchronousXopt

- environment.yml
- requirements.txt
We will maintain Xopt compatibility with Python 3.9.19 by restricting BoTorch version to <=0.10.0.
Once prod can support Python>=3.10, we will update the code for compatibility with BoTorch>=0.11.0.
> Include requirement botorch<=0.10.0 for compatibility with python 3.9

- .github/actions/conda-setup/action.yml
- environment.yml
- environment_.yml
- pyproject.toml
- updated pyproject.toml
- added deps based on environment.yml
-  `dask` and `mpi4py` added to dev deps based on conda-forge recipe
- updated environment.yml
- matplotlib moved from deps to "regular" deps based on feedback from Ryan
- adjusted `mkdocs-jupyter` install since [#31](https://github.com/conda-forge/mkdocs-jupyter-feedstock/issues/31) is resolved
- updated conda-setup/action.yml to support pip install if/when environment.yml is not available
- when environment.yml is not available, the conda runner will install python=3.12 by default, checking for this regardless of the cache existing avoids errors wrt the python version
- added binaries needed for MPI when a pip install is done
> Fixes #249, adds dependencies for PyPI packaging and updates CI tests

- xopt/generators/bayesian/bayesian_generator.py
- xopt/generators/bayesian/mobo.py
- xopt/numerical_optimizer.py
- xopt/resources/test_functions/zdt.py
- xopt/tests/generators/bayesian/test_mobo.py
- xopt/tests/test_numerical_optimizer.py
- xopt/tests/test_vocs.py
- xopt/vocs.py
- enhances multi-objective bayesian optimization algorithms by adding an `use_pf_as_initial_points` flag which uses points on the pareto frontier to initialize optimization of the EHVI acquisition function which results in substantial speed-up of convergence to the pareto front in high-dimensional input spaces
> Mobo enhancement

- xopt/generators/ga/cnsga.py
This PR includes the following two changes proposed to allow users on Windows to run the CNSGA generator with file output.
- `CNSGAGenerator.write_offspring` has been updated to avoid the colon character in filenames similarly to `write_population` in #251
- The string replacement for colon characters in filenames has been moved to only apply to the timestamp. This avoids causing problems when `self.output_path` looks like "C:\Users\yourname\project\dir"
> CNSGA Output Filenames

- xopt/generators/bayesian/visualize.py
Within the `visualize_model` function, `plt.subplot()` returns two different types depending on how many plots are passed into the function as an argument. The tuple that is returned contains the `Figure` and `Axes`.
When passed in multiple plots, `plt.subplot()` returns `tuple[Figure, ndarray]` where the `ndarray` contains multiple `Axes` for each plot.
The unhandled case is when only one plot is passed into `plt.subplot()` which returns `tuple[Figure, Axes]` where the return type of `Axes` is unhandled in the current code and will throw and exception later in the function.
This was causing a crash within the BO Visualizer extension within Badger when trying to visualize only one chart.
You can force the return type of `plt.subplot()` to return `tuple[Figure, ndarray]` no matter how many …
> Fixed unhandled case when only one plot is passed into plt.subplot for the bayesian visualize_model function

- .github/workflows/lint.yml
Not sure why this happened (maybe some upstream updates w/ mamba or the problem packages) but this seems to fix it, and it's consistent with how we're installing packages in the env in the conda action.
> Update lint.yml to mamba install

- xopt/generators/bayesian/expected_improvement.py
- addresses a bug where EI didn't overwrite `get_acquisition()` method as expected (and necessary)
> Fix bug when using EI with constraints

- .github/workflows/gh-pages.yml
To deploy site uploaded with actions/upload-pages-artifact@v3, we need actions/deploy-pages@v4 or newer.
> Update gh-pages.yml deploy version

- .github/actions/conda-setup/action.yml
- pyproject.toml
I pinned the mamba version until `setup-miniconda` merges in the conda/mamba fix. I also pinned the botorch version until we adjust our tests to v0.13.0 (errors observed on Badger CI/CD).
> Pin mamba and botorch

- xopt/generators/bayesian/turbo.py
- xopt/tests/generators/bayesian/test_turbo.py
Sign discrepancy between data and best value for maximization objectives causes turbo controller to make opposite actions. Didn't check other turbo classes - might be issues there too. Discovered with unit testing mirror functions (negation of eval_f and objective + comparing convergence) - need to add later.
> Turbo maximization sign fix

- docs/api/generators/bayesian.md
BAX was missing from the API documentation.
> Add BAX in the automated API documentation

- xopt/generators/ga/nsga2.py
- xopt/generators/utils.py
- xopt/tests/generators/ga/test_nsga2.py
Line 89 in `xopt/generators/ga/nsga2.py` is the following.
```python
pop_f[~np.isfinite(pop_g)] = 1e300 
```
It should have read as this.
```python
pop_f[~np.isfinite(pop_f)] = 1e300 
```
This will cause an error in the specific case that a problem has more than one constraint and the number of constraints is not equal to the number of objectives. 
This PR adds a unit test that triggers on the bug, fixes the bug, and refactors how NaNs are handled in `crowded_comparison_argsort`. A complete set of changes are the following.
- New unit test `test_crowded_comparison_argsort` which errors out due to the previous bug. It test a set of populations and their manually calculated fitness orderings against the function. The cases include instances with more than one constraint and a different …
> NSGA2 Generator NaN Handling in `crowded_comparison_argsort` Bugfix

- xopt/generators/bayesian/bayesian_generator.py
- xopt/tests/generators/bayesian/test_upper_confidence_bound.py
Wrong bounds and unwrapped acquisition functions were used in the optimum search, causing issues. Fixed and adjusted bounds calc to use better indexing.
Fixes #313
> Fix optimum search with fixed features

- xopt/generators/bayesian/bax/acquisition.py
The previous call to model posterior was generating an error due to improper input formatting. This change corrects it.
> Fix model posterior call.

- xopt/generators/__init__.py
- xopt/generators/bayesian/bayesian_generator.py
- xopt/generators/bayesian/utils.py
Objective:
Adds methods to `BayesianGenerator` class to allow retrieval of compatible `numerical optimizers` and `turbo controllers` for use with new badger feature https://github.com/xopt-org/Badger/pull/206
Features:
- Adds `_compatible_numerical_optimizers` private variable to `BayesianGenerator` class
- Adds getter methods to return list of compatible classes for both `numerical optimizer` and `turbo controller`
- Fixes pydantic validation
> Additions to BayesianGenerator to support BadgerPydanticEditor in Badger

- docs/algorithms.md
This PR adds links from the algorithms page to the documentation page for each generator. Some missing generators are added to the algorithms page: 
- `NSGA2Generator`
- `LatinHypercubeGenerator`
> Add Links to Algorithms Page; Missing Generators
